[package]
name = "Socket_Tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
enigo = "0.3.0"
once_cell = "1.20.2"
